# -*- coding: utf-8 -*-
#
# temporary conf.py to create simple redirect page
#  on readthedocs to the github pydicom documentation
import sys
import os

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'rtfd-index'

# General information about the project.
project = u'pydicom'
copyright = u'2008-2018, Darcy Mason and pydicom contributors'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']

# Custom style
html_style = 'css/pydicom.css'


# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
html_theme = 'default'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "assets/img/logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "assets/img/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'pydicomdoc'

